name: tiktok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  video_player: ^2.9.1
  cached_network_image: ^3.2.0
  video_thumbnail: ^0.5.0
  chewie: ^1.3.0

dev_dependencies: 
  #flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

